apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql
      image: 737372589521.dkr.ecr.us-east-1.amazonaws.com/assignment2-repo:mysql-v0.1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "assignment2"
