apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod2
  labels: 
    app: employees
    version: v2
spec:
  containers:
    - name: web-app
      image: 737372589521.dkr.ecr.us-east-1.amazonaws.com/assignment2-repo-version2:application-v0.1
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: 10.244.0.5
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "assignment2"

